
services:
  # 🚀 BACKEND
  backend:
    container_name: backend-riego
    build: .
    restart: always
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      # CORRECCIÓN AQUÍ: Usamos los mismos nombres que en el código (DB_...)
      # Y forzamos el host a "mariadb" (el nombre del servicio de abajo)
      - DB_HOST=mariadb  
      - DB_USER=root
      - DB_PASS=admin
      - DB_NAME=riego
      - FIREBASE_ENABLED=true
      - MQTT_ENABLED=true
      - MQTT_BROKER_URL=mqtt://mosquitto:1883 
      - MQTT_TOPICS=sensors/#
    depends_on:
      - mariadb
      - mosquitto
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev

# 🦟 MOSQUITTO (Nuevo servicio)
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    restart: always
    ports:
      - "1883:1883"  # Puerto para sensores (Arduino/Simulador)
      - "9001:9001"  # Puerto WebSockets (Opcional)
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  # 🗄️ MARIADB
  mariadb:
    image: mariadb:11
    container_name: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=riego
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      # ARCHIVO 1: Estructura (Le llamamos 01 para que vaya primero)
      - ./riego.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
      # ARCHIVO 2: Datos (Le llamamos 02 para que vaya después)
      - ./seed.sql:/docker-entrypoint-initdb.d/02-seed.sql:ro
      
  # 🧰 PHPMYADMIN (opcional pero muy útil)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=root
      - PMA_PASSWORD=admin
    depends_on:
      - mariadb


volumes:
  mariadb_data:

